# GitHub Easy Mobile - Simple Build Fix
workflows:
  android-debug:
    name: Android Debug Build (Simple)
    max_build_duration: 30
    
    build:
      - name: Setup environment
        script: |
          sudo apt-get update && sudo apt-get install -y openjdk-17-jdk
          export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
          
      - name: Build APK
        script: |
          chmod +x gradlew
          ./gradlew clean assembleDebug
          
      - name: Show result
        script: |
          ls -la app/build/outputs/apk/debug/app-debug.apk 2>/dev/null || echo "APK not found"
          
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk