#!/bin/bash

# GitHub Easy Mobile - CodeMagic Setup Script
# این اسکریپت پروژه را برای CodeMagic آماده می‌کند

echo "🚀 در حال آماده‌سازی پروژه برای CodeMagic..."

# بررسی وجود فایل‌های ضروری
echo "✅ بررسی فایل‌های ضروری..."

required_files=(
    "codemagic.yaml"
    "gradle/wrapper/gradle-wrapper.properties"
    "gradle/wrapper/gradle-wrapper.jar"
    "gradlew"
    "app/build.gradle"
)

missing_files=()

for file in "${required_files[@]}"; do
    if [ ! -f "$file" ]; then
        missing_files+=("$file")
    fi
done

if [ ${#missing_files[@]} -gt 0 ]; then
    echo "❌ فایل‌های مفقود:"
    printf '   %s\n' "${missing_files[@]}"
    exit 1
fi

echo "✅ همه فایل‌ها موجود است!"

# بررسی و تست Gradle Wrapper
echo "🔧 تست Gradle Wrapper..."
chmod +x gradlew
./gradlew --version

if [ $? -eq 0 ]; then
    echo "✅ Gradle Wrapper درست کار می‌کند!"
else
    echo "❌ خطا در Gradle Wrapper"
    exit 1
fi

# ساخت keystore برای release (اختیاری)
echo ""
echo "🔑 آیا می‌خواهید keystore برای release بسازید؟ (y/n)"
read -r create_keystore

if [ "$create_keystore" = "y" ] || [ "$create_keystore" = "Y" ]; then
    echo "🔐 در حال ساخت keystore..."
    
    keystore_name="release.keystore"
    
    if [ -f "$keystore_name" ]; then
        echo "⚠️  keystore موجود است، می‌خواهید بازنویسی شود؟ (y/n)"
        read -r overwrite
        if [ "$overwrite" != "y" ] && [ "$overwrite" != "Y" ]; then
            echo "🚀 آماده برای آپلود به CodeMagic!"
            exit 0
        fi
    fi
    
    echo "ℹ️  اطلاعات keystore را وارد کنید:"
    keytool -genkey -v -keystore "$keystore_name" -keyalg RSA -keysize 2048 -validity 10000 -alias release
    
    echo ""
    echo "✅ Keystore ساخته شد!"
    echo "📋 در CodeMagic این اطلاعات را وارد کنید:"
    echo "   - فایل keystore: $keystore_name"
    echo "   - Alias: release"
    echo "   - رمز عبور keystore: (همان کلمه عبوری که وارد کردید)"
fi

echo ""
echo "🎉 پروژه آماده برای CodeMagic است!"
echo ""
echo "📋 مراحل بعدی:"
echo "1. پروژه را در GitHub آپلود کنید"
echo "2. در CodeMagic ثبت نام کنید"
echo "3. مخزن GitHub را به CodeMagic متصل کنید"
echo "4. Build را شروع کنید"
echo ""
echo "📖 برای راهنمای کامل، فایل CODEMAGIC_GUIDE.md را مطالعه کنید"

# ایجاد فایل زمان‌بندی برای git
echo ""
echo "📦 آیا می‌خواهید پروژه را در Git آماده کنید؟ (y/n)"
read -r prepare_git

if [ "$prepare_git" = "y" ] || [ "$prepare_git" = "Y" ]; then
    echo "📋 در حال آماده‌سازی Git..."
    
    if [ ! -f ".gitignore" ]; then
        cat > .gitignore << EOF
# Built application files
*.apk
*.aab
*.ap_
*.aab

# Files for the ART/Dalvik VM
*.dex

# Java class files
*.class

# Generated files
bin/
gen/
out/
#  Uncomment the following line in case you need and you don't have the release build type files in your app
# release/

# Gradle files
.gradle/
build/

# Local configuration file (sdk path, etc)
local.properties

# Proguard folder generated by Eclipse
proguard/

# Log Files
*.log

# Android Studio Navigation editor temp files
.navigation/

# Android Studio captures folder
captures/

# IntelliJ
*.iml
.idea/workspace.xml
.idea/tasks.xml
.idea/gradle.xml
.idea/assetWizardSettings.xml
.idea/dictionaries
.idea/libraries
# Android Studio 3 in .gitignore file.
.idea/caches
.idea/modules.xml
# Comment next line if keeping position of elements in Navigation Editor is relevant for you
.idea/navEditor.xml

# Keystore files
# Uncomment the following lines if you do not want to check your keystore files in.
#*.jks
#*.keystore

# External native build folder generated in Android Studio 2.2 and later
.externalNativeBuild
.cxx/

# Google Services (e.g. APIs or Firebase)
# google-services.json

# Freeline
freeline.py
freeline/
freeline_project_description.json

# fastlane
fastlane/report.xml
fastlane/Preview.html
fastlane/screenshots
fastlane/test_output
fastlane/readme.md

# Version control
.vcs.xml

# lint
lint/intermediates/
lint/generated/
lint/outputs/
lint/tmp/
# lint/reports/

# Android Profiling
*.hprof

# Keystore files
#*release.keystore
*.jks
*.keystore

# Mac system files
.DS_Store
EOF
        echo "✅ فایل .gitignore ایجاد شد"
    fi
    
    git init
    git add .
    git commit -m "Initial commit - GitHub Easy Mobile for CodeMagic"
    
    echo ""
    echo "✅ Git آماده است!"
    echo "🔗 حالا مخزن GitHub خود را ایجاد کنید و این دستورات را اجرا کنید:"
    echo "   git remote add origin YOUR_GITHUB_REPO_URL"
    echo "   git branch -M main"
    echo "   git push -u origin main"
fi

echo ""
echo "🚀 پروژه کاملاً آماده برای CodeMagic است!"